Actual CRAN test outcomes (converted to ANSI): ```     -- Failure (test-helper_functions2.R:19:5): normPath ---------------------------     normPath\("\."\) does not match "d:/RCompile/CRANincoming/R-devel/multiversion.Rcheck/tests/testthat".     Actual value: "D:/RCompile/CRANincoming/R-devel/multiversion\.Rcheck/tests/testthat"     Backtrace:
     1. +-testthat::expect_match(normPath("."), gsub("\\\\", "/", getwd())) test-helper_functions2.R:19:4
     2.   +-testthat:::expect_match_(...)
    -- Failure (test-tarball_installation.R:96:9): install to temp lib and convert to mv lib --
    msg\[3\] does not match "package.a: 24$".
    Actual value: "package\.a: 20"
    Backtrace:

     1. +-testthat::expect_match(msg[3], "package.a: 24$") test-tarball_installation.R:96:8
     2.   +-testthat:::expect_match_(...)
    -- Failure (test-tarball_installation.R:114:9): install to temp lib and convert to mv lib --
    msg\[6\] does not match "package.a: 24$".
    Actual value: "package\.a: 20"
    Backtrace:

     1. +-testthat::expect_match(msg[6], "package.a: 24$") test-tarball_installation.R:114:8
     2.   +-testthat:::expect_match_(...)
    -- Failure (test-tarball_installation.R:123:9): install to temp lib and convert to mv lib --
    msg\[3\] does not match "package.a: 24, testit: 22$".
    Actual value: "package\.a: 20, testit: 22"
    Backtrace:

     1. +-testthat::expect_match(msg[3], "package.a: 24, testit: 22$") test-tarball_installation.R:123:8
     2.   +-testthat:::expect_match_(...)

    [ FAIL 4 | WARN 0 | SKIP 0 | PASS 213 ]
    Error: Test failures
```